export const data = [
  {
    numberRequest: "3420",
    numberPosition: "123",
    tradeType: "123",
    tradeSection:
      "Секция реализации высоколиквидной продукции предприятий-монополистов",
    groupItems: "Сельхозпродукция и продукция её переработки",
    tnved: "1206009900 - Семена подсолнечника, дробленые или недробленые",
    tradeView: "Слот",
    typeBoxing: "канистра",
    boxingCurrency: "тонна",
    size: "1 000 т",
    lotSize: "100 т",
    sumLots: "10 лотов",
    basePrice: "50 000,00 сум",
    allSum: "50 000 000,00 сум",
    countryHappening: "Узбекистан",
    itemAdress: "Gorod takoy, ulitsa takaya, xonadon topib olarsan 777",
    basisOrdering: "EXW - самовывоз",
    srokOrdering: "10 банк. дней",
    viewSdelka: "Слот",
    minPrice: "-",
    maxPrice: "-",
    percentFromSeller: "0",
    percentFromBuyer: "3",
    uslovie:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    vidTrade: 'Внутренный',
    client: 'ООО "DAVRON BOBO"',
    usloviePrice: 'нет ограничений по допустимой цене покупки',
    sum: '5 000 000',
    priceValue: '5000   '
  },
];
